version: "3"

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - sh
      - -c
      - python app.py
    volumes:
      - .:/app

  test_myapp:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - sh
      - -c
      - python test_app.py
    volumes:
      - .:/app
